branch-defaults:
  live-v4:
    environment: apiv4-live
  v4:
    environment: clients-apiv4
    group_suffix: null
global:
  application_name: apiv4
  branch: null
  default_ec2_keyname: cambrian-servers
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
